### ISSUE TITLE
Typings for 'tweakpane' require '@tweakpane/core'

### ISSUE THREAD

**Issue by donmccurdy** [cocopon/tweakpane#335]
When upgrading to v3 of Tweakpane, I'm finding that Typescript cannot understand the type definitions fully if I've only installed the `tweakpane` package, with error, `Property 'addInput' does not exist on type 'Pane'` —

![Screen Shot 2021-07-18 at 8 59 27 PM](https://user-images.githubusercontent.com/1848368/126100880-a6a995cb-3af7-4ac9-8363-b97f6b5f5b71.png)

Manually installing `@tweakpane/core` to my project will fix those errors, but I doubt that's intended? I believe that `@tweakpane/core` should be included as a production dependency of `tweakpane`, even though it's only used for type definitions.

**Comment by donmccurdy** [comment]
Oops, I see this is documented: https://cocopon.github.io/tweakpane/getting-started.html 

Never mind! :)

**Comment by cocopon** [comment]
Yeah it's intentional. JavaScript project doesn't require type definitions, so I don't add `@tweakpane/core` to the dependency.
